name: Node.js CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build # รอให้งาน build สำเร็จก่อนที่จะเริ่มต้นทำงาน

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout main branch
        run: git checkout main

      - name: Pull latest changes from main
        run: git pull origin main

      - name: Merge main into gh-pages
        run: git merge --no-commit --no-ff main

      - name: Configure Git
        run: |
          git config --global user.email "akkewach.yodsomboon@gmail.com"
          git config --global user.name "akkewacheiei"

      - name: Push changes to gh-pages
        run: |
          git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:gh-pages
