name: Node.js CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build # รอให้งาน build สำเร็จก่อนที่จะเริ่มต้นทำงาน

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest changes from main
        run: git fetch origin main:main

      - name: Merge main into gh-pages
        run: git merge --no-commit --no-ff main

      - name: Copy index.html
        run: cp main/index.html .

      - name: Commit changes
        run: |
          git add index.html
          git commit -m "Update index.html from main"
      
      - name: Push changes to gh-pages
        run: git push origin HEAD:gh-pages
